import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedCertificadodeRegistroWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedRegistrodeNegcioWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedBtnUploadPhotoWidget5.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedRGouPassaporteWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedDocumentosWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/Generated4Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedBtngoWidget8.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/Generated3Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget3.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedBtnUploadPhotoWidget4.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/Generated1Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/GeneratedCertificadodeAntecedentesCriminaisWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroenviodedocumentoswidget/generated/Generated2Widget.dart';

/* Frame Cadastro - Envio de documentos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroEnviodedocumentosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget3(),
              ),
              Positioned(
                left: 86.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 157.0,
                height: 34.0,
                child: GeneratedDocumentosWidget(),
              ),
              Positioned(
                left: 115.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 24.0,
                child: GeneratedRGouPassaporteWidget(),
              ),
              Positioned(
                left: 86.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 197.0,
                height: 24.0,
                child: GeneratedCertificadodeRegistroWidget(),
              ),
              Positioned(
                left: 86.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 24.0,
                child: GeneratedRegistrodeNegcioWidget(),
              ),
              Positioned(
                left: 86.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 46.0,
                child: GeneratedCertificadodeAntecedentesCriminaisWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 619.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedBtnUploadPhotoWidget4(),
              ),
              Positioned(
                left: 83.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 182.0,
                height: 45.0,
                child: GeneratedBtnUploadPhotoWidget5(),
              ),
              Positioned(
                left: 77.0,
                top: 69.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget8(),
              ),
              Positioned(
                left: 61.0,
                top: 119.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 27.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 223.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 27.0,
                child: Generated2Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 27.0,
                child: Generated3Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 27.0,
                child: Generated4Widget(),
              )
            ]),
      ),
    ));
  }
}
