import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontaverificadawidget/generated/GeneratedChecked31Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontaverificadawidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget4.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontaverificadawidget/generated/GeneratedGroup51Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontaverificadawidget/generated/GeneratedParabnssuacontaestverificadaWidget.dart';

/* Frame Cadastro - Conta Verificada
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroContaVerificadaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget4(),
              ),
              Positioned(
                left: 37.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedGroup51Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 21.0,
                child: GeneratedParabnssuacontaestverificadaWidget(),
              ),
              Positioned(
                left: 174.0,
                top: 214.0,
                right: null,
                bottom: null,
                width: 66.0,
                height: 66.0,
                child: GeneratedChecked31Widget(),
              )
            ]),
      ),
    ));
  }
}
