import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedGroup43Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedInformeasinformaesabaixoparacadastrarseWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedGroup44Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedBtngoWidget17.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedGroup47Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedGroup48Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedGroup45Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedGroup46Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedCriesuacontaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedVoltarWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget1/generated/GeneratedGroup20Widget1.dart';

/* Frame Cadastro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 537.0,
                              top: 316.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup20Widget1(),
                            ),
                            Positioned(
                              left: 537.0,
                              top: 370.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup44Widget(),
                            ),
                            Positioned(
                              left: 537.0,
                              top: 424.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup45Widget(),
                            ),
                            Positioned(
                              left: 615.0,
                              top: 186.0,
                              right: null,
                              bottom: null,
                              width: 214.0,
                              height: 32.0,
                              child: GeneratedCriesuacontaWidget(),
                            ),
                            Positioned(
                              left: 537.0,
                              top: 700.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 47.0,
                              child: GeneratedGroup43Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.5902777777777778;

                                final double height =
                                    constraints.maxHeight * 0.0234375;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth * 0.35625,
                                      y: constraints.maxHeight * 0.2490234375,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedInformeasinformaesabaixoparacadastrarseWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 537.0,
                              top: 478.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup46Widget(),
                            ),
                            Positioned(
                              left: 537.0,
                              top: 586.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup48Widget(),
                            ),
                            Positioned(
                              left: 537.0,
                              top: 532.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup47Widget(),
                            ),
                            Positioned(
                              left: 94.0,
                              top: 85.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 62.0,
                              child: GeneratedBtngoWidget17(),
                            ),
                            Positioned(
                              left: 79.0,
                              top: 42.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 32.0,
                              child: GeneratedVoltarWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
