import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedSenhaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedAindanosecadastrouCadastreseWidget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedBtngoWidget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedGroup66Widget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedEsqueceusuasenhaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedloginwidget/generated/GeneratedRealizeseuloginWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 64.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 52.0,
                child: GeneratedGroup66Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 19.0,
                child: GeneratedAindanosecadastrouCadastreseWidget(),
              ),
              Positioned(
                left: 139.0,
                top: 473.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 19.0,
                child: GeneratedEsqueceusuasenhaWidget(),
              ),
              Positioned(
                left: 87.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 59.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 44.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 22.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 22.0,
                child: GeneratedSenhaWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 24.0,
                child: GeneratedRealizeseuloginWidget(),
              )
            ]),
      ),
    ));
  }
}
