import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/GeneratedBacktoHomeWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/GeneratedPrximospassosWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/Generated1Imprimireassinarocontrato2Fazeruploaddocontratoassinad.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/GeneratedDOWNLOADDOCONTRATOWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget5.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/GeneratedRectangle171Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/GeneratedGroup34Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/GeneratedVocestquaselWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrocontratoassinadowidget/generated/GeneratedGroup33Widget.dart';

/* Frame Cadastro - Contrato assinado
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroContratoassinadoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget5(),
              ),
              Positioned(
                left: 136.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 24.0,
                child: GeneratedBacktoHomeWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 151.0,
                height: 21.0,
                child: GeneratedVocestquaselWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 286.0,
                height: 40.0,
                child:
                    Generated1Imprimireassinarocontrato2Fazeruploaddocontratoassinad(),
              ),
              Positioned(
                left: 35.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 204.0,
                height: 31.0,
                child: GeneratedPrximospassosWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle171Widget(),
              ),
              Positioned(
                left: 84.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 245.0,
                height: 24.0,
                child: GeneratedDOWNLOADDOCONTRATOWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 55.0,
                child: GeneratedGroup33Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedGroup34Widget(),
              )
            ]),
      ),
    ));
  }
}
