import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedGroup41Widget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedCalendar111Widget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedGroup38Widget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedGroupWidget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedGroup36Widget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedGroup40Widget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialapsloginwidget/generated/GeneratedGroup39Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Tela inicial, após login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelainicialapsloginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.06569343065693431;

                  final double height =
                      constraints.maxHeight * 0.036935704514363885;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.170316301703163,
                        y: constraints.maxHeight * 0.09302325581395349,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroupWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 37.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 55.0,
                child: GeneratedGroup26Widget(),
              ),
              Positioned(
                left: 179.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 196.0,
                height: 55.0,
                child: GeneratedGroup27Widget(),
              ),
              Positioned(
                left: 364.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 23.0,
                child: GeneratedCalendar111Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 209.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 85.0,
                child: GeneratedGroup36Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 85.0,
                child: GeneratedGroup38Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 407.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 85.0,
                child: GeneratedGroup39Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 85.0,
                child: GeneratedGroup40Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 85.0,
                child: GeneratedGroup41Widget(),
              )
            ]),
      ),
    ));
  }
}
