import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget2/generated/GeneratedEsqueciminhasenhaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget2/generated/GeneratedVoltarWidget.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget2/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget2/generated/GeneratedColoqueseuemaileenviaremosumlinkpararesetarsuasenhaWidg.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget2/generated/GeneratedGroup43Widget.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget2/generated/GeneratedBtngoWidget16.dart';

/* Frame Esqueceu a senha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEsqueceuasenhaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 529.0,
                              top: 504.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup20Widget(),
                            ),
                            Positioned(
                              left: 557.0,
                              top: 384.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 32.0,
                              child: GeneratedEsqueciminhasenhaWidget(),
                            ),
                            Positioned(
                              left: 529.0,
                              top: 594.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 47.0,
                              child: GeneratedGroup43Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.5902777777777778;

                                final double height =
                                    constraints.maxHeight * 0.0234375;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.28888888888888886,
                                      y: constraints.maxHeight * 0.4375,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedColoqueseuemaileenviaremosumlinkpararesetarsuasenhaWidg(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 88.0,
                              top: 84.0,
                              right: null,
                              bottom: null,
                              width: 70.0,
                              height: 62.0,
                              child: GeneratedBtngoWidget16(),
                            ),
                            Positioned(
                              left: 74.0,
                              top: 40.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 32.0,
                              child: GeneratedVoltarWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
