import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedRectangle173Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitNuncblan1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedRectangle172Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedPrximoWidget4.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedGroup23Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget7.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedBtngoWidget10.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedTermosecondiesWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget1/generated/GeneratedRectangle174Widget6.dart';

/* Frame Cadastro - Termos e Condições
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroTermoseCondiesWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget7(),
              ),
              Positioned(
                left: 370.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 4.0,
                height: 414.0,
                child: GeneratedRectangle172Widget1(),
              ),
              Positioned(
                left: 77.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 31.0,
                child: GeneratedTermosecondiesWidget1(),
              ),
              Positioned(
                left: 77.0,
                top: 58.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget10(),
              ),
              Positioned(
                left: 37.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle173Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 27.0,
                child: GeneratedPrximoWidget4(),
              ),
              Positioned(
                left: 43.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 416.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitNuncblan1(),
              ),
              Positioned(
                left: 37.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 50.0,
                child: GeneratedGroup23Widget1(),
              ),
              Positioned(
                left: 370.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 4.0,
                height: 119.0,
                child: GeneratedRectangle174Widget6(),
              )
            ]),
      ),
    ));
  }
}
