import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedRectangle3Widget5.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedBtngoWidget12.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget9.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedDigiteocdigode4digitosWidget.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedBacktoHomeWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedRectangle2Widget4.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedVerificaodeemailWidget.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedNorecebeuEnviarnovamenteWidget.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedverificaodeemailwidget/generated/GeneratedRectangle4Widget.dart';

/* Frame Verificação de E-mail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerificaodeEmailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget9(),
              ),
              Positioned(
                left: 90.0,
                top: 34.0,
                right: null,
                bottom: null,
                width: 273.0,
                height: 29.0,
                child: GeneratedVerificaodeemailWidget(),
              ),
              Positioned(
                left: 114.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 19.0,
                child: GeneratedDigiteocdigode4digitosWidget(),
              ),
              Positioned(
                left: 84.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 71.0,
                child: GeneratedRectangle2Widget4(),
              ),
              Positioned(
                left: 147.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 71.0,
                child: GeneratedRectangle3Widget5(),
              ),
              Positioned(
                left: 210.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 71.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 273.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 71.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 58.0,
                top: 67.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget12(),
              ),
              Positioned(
                left: 145.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 53.0,
                child: GeneratedNorecebeuEnviarnovamenteWidget(),
              ),
              Positioned(
                left: 139.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 24.0,
                child: GeneratedBacktoHomeWidget1(),
              ),
              Positioned(
                left: 41.0,
                top: 631.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedGroup35Widget(),
              )
            ]),
      ),
    ));
  }
}
