import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedMENULATERALWidget.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedFramedoGoogleMapscomarotaselecionadaWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedEscolhaoendereodeorigemWidget.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedGroup33Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedVectorWidget15.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedRectangle4Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedEscolhaoendereodedestinoWidget.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/dailytripapp/generatedpginainicialapsologinwidget/generated/GeneratedInformearotaWidget.dart';

/* Frame Página inicial após o login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPginainicialapsologinWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 253.0,
                              top: 55.0,
                              right: null,
                              bottom: null,
                              width: 207.0,
                              height: 32.0,
                              child: GeneratedInformearotaWidget(),
                            ),
                            Positioned(
                              left: 253.0,
                              top: 120.0,
                              right: null,
                              bottom: null,
                              width: 1116.0,
                              height: 79.0,
                              child: GeneratedRectangle4Widget1(),
                            ),
                            Positioned(
                              left: 253.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 1116.0,
                              height: 337.0,
                              child: GeneratedRectangle6Widget2(),
                            ),
                            Positioned(
                              left: 761.0,
                              top: 109.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 101.0,
                              child: GeneratedEllipse4Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.025694444444444443;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        37.0;

                                double percentHeight = 0.0234375;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        24.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.5756944444444444,
                                      translateY:
                                          constraints.maxHeight * 0.1435546875,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedVectorWidget15())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 270.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 320.0,
                              height: 29.0,
                              child: GeneratedEscolhaoendereodeorigemWidget(),
                            ),
                            Positioned(
                              left: 582.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 495.0,
                              height: 29.0,
                              child:
                                  GeneratedFramedoGoogleMapscomarotaselecionadaWidget(),
                            ),
                            Positioned(
                              left: 1024.0,
                              top: 146.0,
                              right: null,
                              bottom: null,
                              width: 326.0,
                              height: 29.0,
                              child: GeneratedEscolhaoendereodedestinoWidget(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 211.0,
                              height: 1024.0,
                              child: GeneratedMENULATERALWidget(),
                            ),
                            Positioned(
                              left: 1085.0,
                              top: 668.0,
                              right: null,
                              bottom: null,
                              width: 284.0,
                              height: 57.0,
                              child: GeneratedGroup33Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
