import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedCampoEmailWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedBtngoWidget6.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedSenhaWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedInformaespessoaisWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedTelefoneWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedNomeWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedBtnUploadPhotoWidget2.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrowidget/generated/GeneratedRectangle8Widget.dart';

/* Frame Cadastro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 82.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 31.0,
                child: GeneratedInformaespessoaisWidget(),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget(),
              ),
              Positioned(
                left: 209.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 55.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 55.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 60.0,
                top: 276.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 22.0,
                child: GeneratedNomeWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 320.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle8Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 338.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 22.0,
                child: GeneratedTelefoneWidget(),
              ),
              Positioned(
                left: 38.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 60.0,
                top: 400.0,
                right: null,
                bottom: null,
                width: 47.0,
                height: 22.0,
                child: GeneratedSenhaWidget1(),
              ),
              Positioned(
                left: 37.0,
                top: 628.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedBtnUploadPhotoWidget2(),
              ),
              Positioned(
                left: 64.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget6(),
              ),
              Positioned(
                left: 38.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedCampoEmailWidget(),
              ),
              Positioned(
                left: 108.0,
                top: 120.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget1(),
              )
            ]),
      ),
    ));
  }
}
