import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedTermosecondiesWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedRectangle174Widget5.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedPrximoWidget3.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget6.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedRectangle173Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedBtngoWidget9.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedLoremipsumdolorsitametconsecteturadipiscingelitNuncblan.dart';
import 'package:flutterapp/dailytripapp/generatedcadastrotermosecondieswidget/generated/GeneratedRectangle172Widget.dart';

/* Frame Cadastro - Termos e Condições
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroTermoseCondiesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget6(),
              ),
              Positioned(
                left: 370.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 4.0,
                height: 414.0,
                child: GeneratedRectangle172Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 31.0,
                child: GeneratedTermosecondiesWidget(),
              ),
              Positioned(
                left: 65.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget9(),
              ),
              Positioned(
                left: 37.0,
                top: 621.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle173Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 637.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 27.0,
                child: GeneratedPrximoWidget3(),
              ),
              Positioned(
                left: 43.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 322.0,
                height: 416.0,
                child:
                    GeneratedLoremipsumdolorsitametconsecteturadipiscingelitNuncblan(),
              ),
              Positioned(
                left: 37.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 374.0,
                height: 42.0,
                child: GeneratedGroup23Widget(),
              ),
              Positioned(
                left: 370.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 4.0,
                height: 119.0,
                child: GeneratedRectangle174Widget5(),
              )
            ]),
      ),
    ));
  }
}
