import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget/generated/GeneratedRecuperaodesenhaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget/generated/GeneratedBtngoWidget13.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget/generated/GeneratedEmailWidget2.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget/generated/GeneratedImage1Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget/generated/GeneratedGroup66Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget/generated/GeneratedInformeseuemaileenviaremosumlinkpararesetarsuasenhaWidg.dart';

/* Frame Esqueceu a senha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEsqueceuasenhaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 64.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget13(),
              ),
              Positioned(
                left: 44.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 52.0,
                child: GeneratedGroup66Widget1(),
              ),
              Positioned(
                left: 87.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 59.0,
                child: GeneratedImage1Widget1(),
              ),
              Positioned(
                left: 44.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle9Widget1(),
              ),
              Positioned(
                left: 65.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 22.0,
                child: GeneratedEmailWidget2(),
              ),
              Positioned(
                left: 70.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 46.0,
                child:
                    GeneratedInformeseuemaileenviaremosumlinkpararesetarsuasenhaWidg(),
              ),
              Positioned(
                left: 66.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 31.0,
                child: GeneratedRecuperaodesenhaWidget(),
              )
            ]),
      ),
    ));
  }
}
