import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedImage1Widget2.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedBtngoWidget14.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedDigiteocdigode4digitosWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedGroup35Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedFoienviadoumemailcomumcdigorecuperaodasenhaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedNorecebeuEnviarnovamenteWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedesqueceuasenhawidget1/generated/GeneratedRecuperaodesenhaWidget1.dart';

/* Frame Esqueceu a senha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEsqueceuasenhaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 64.0,
                top: 63.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget14(),
              ),
              Positioned(
                left: 87.0,
                top: 37.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 59.0,
                child: GeneratedImage1Widget2(),
              ),
              Positioned(
                left: 45.0,
                top: 113.0,
                right: null,
                bottom: null,
                width: 324.0,
                height: 46.0,
                child:
                    GeneratedFoienviadoumemailcomumcdigorecuperaodasenhaWidget(),
              ),
              Positioned(
                left: 100.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 19.0,
                child: GeneratedDigiteocdigode4digitosWidget1(),
              ),
              Positioned(
                left: 70.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 71.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 133.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 71.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 196.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 71.0,
                child: GeneratedRectangle8Widget1(),
              ),
              Positioned(
                left: 259.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 71.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 131.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 53.0,
                child: GeneratedNorecebeuEnviarnovamenteWidget1(),
              ),
              Positioned(
                left: 44.0,
                top: 625.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedGroup35Widget1(),
              ),
              Positioned(
                left: 66.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 31.0,
                child: GeneratedRecuperaodesenhaWidget1(),
              )
            ]),
      ),
    ));
  }
}
