import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialwidget/generated/GeneratedBtnUploadPhotoWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialwidget/generated/GeneratedAmareloFofoAnimalLogotipo21Widget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialwidget/generated/GeneratedBtnUploadPhotoWidget.dart';
import 'package:flutterapp/dailytripapp/generatedtelainicialwidget/generated/GeneratedAmareloFofoAnimalLogotipo1Widget.dart';

/* Component Tela inicial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelainicialWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedBtnUploadPhotoWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 536.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedBtnUploadPhotoWidget1(),
              ),
              Positioned(
                left: 46.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 281.0,
                child: GeneratedAmareloFofoAnimalLogotipo1Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 84.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 290.0,
                child: GeneratedAmareloFofoAnimalLogotipo21Widget(),
              )
            ]),
      ),
    ));
  }
}
