import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedCargaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedPlacadoveculoWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedComprimentoWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedProfundidadeWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget2.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedVector39Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedCategoriaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedVeculoWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedAlturaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedSelecionarWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedEspaodecargaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedBtngoWidget7.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedBtnUploadPhotoWidget3.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget/generated/GeneratedPlacaWidget.dart';

/* Frame Cadastro - Veículo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroVeculoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget2(),
              ),
              Positioned(
                left: 78.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 34.0,
                child: GeneratedVeculoWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 55.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 55.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 267.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 55.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 31.0,
                child: GeneratedProfundidadeWidget(),
              ),
              Positioned(
                left: null,
                top: 296.0,
                right: 145.0,
                bottom: null,
                width: 118.0,
                height: 22.0,
                child: GeneratedComprimentoWidget(),
              ),
              Positioned(
                left: 289.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 62.0,
                height: 31.0,
                child: GeneratedAlturaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 58.0,
                top: 360.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 22.0,
                child: GeneratedCargaWidget(),
              ),
              Positioned(
                left: 58.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 76.0,
                height: 22.0,
                child: GeneratedSelecionarWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedBtnUploadPhotoWidget3(),
              ),
              Positioned(
                left: 37.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 21.0,
                child: GeneratedEspaodecargaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 423.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 24.0,
                child: GeneratedCategoriaWidget(),
              ),
              Positioned(
                left: 329.0,
                top: 474.5,
                right: null,
                bottom: null,
                width: 17.0,
                height: 8.5,
                child: GeneratedVector39Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget7(),
              ),
              Positioned(
                left: 37.0,
                top: 167.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 111.0,
                height: 19.0,
                child: GeneratedPlacadoveculoWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 48.0,
                height: 24.0,
                child: GeneratedPlacaWidget(),
              )
            ]),
      ),
    ));
  }
}
