import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedPrximoWidget5.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedBtngoWidget11.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedDetalhesdoBancoWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedGroup30Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedGroup31Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedInformaesbancriasWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroinformaodebancowidget/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget8.dart';

/* Frame Cadastro - Informação de Banco
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroInformaodeBancoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget8(),
              ),
              Positioned(
                left: 48.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 26.0,
                child: GeneratedInformaesbancriasWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget11(),
              ),
              Positioned(
                left: 37.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 168.0,
                top: 635.0,
                right: null,
                bottom: null,
                width: 82.0,
                height: 27.0,
                child: GeneratedPrximoWidget5(),
              ),
              Positioned(
                left: 36.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 22.0,
                child: GeneratedDetalhesdoBancoWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 202.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedGroup28Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 140.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedGroup29Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedGroup30Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedGroup31Widget(),
              )
            ]),
      ),
    ));
  }
}
