import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedloginpginainicialdaaplicaowidget/generated/GeneratedGroup44Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedloginpginainicialdaaplicaowidget/generated/GeneratedGroup20Widget2.dart';
import 'package:flutterapp/dailytripapp/generatedloginpginainicialdaaplicaowidget/generated/GeneratedGroup43Widget2.dart';
import 'package:flutterapp/dailytripapp/generatedloginpginainicialdaaplicaowidget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/dailytripapp/generatedloginpginainicialdaaplicaowidget/generated/GeneratedRealizeseuloginWidget1.dart';
import 'package:flutterapp/dailytripapp/generatedloginpginainicialdaaplicaowidget/generated/GeneratedBtnUploadPhotoWidget7.dart';
import 'package:flutterapp/dailytripapp/generatedloginpginainicialdaaplicaowidget/generated/GeneratedRealizeseuloginWidget2.dart';

/* Frame Login - página inicial da aplicação
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginpginainicialdaaplicaoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1024.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1440.0,
                      height: 1024.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 472.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup20Widget2(),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 526.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 42.0,
                              child: GeneratedGroup44Widget1(),
                            ),
                            Positioned(
                              left: 580.0,
                              top: 315.0,
                              right: null,
                              bottom: null,
                              width: 248.0,
                              height: 32.0,
                              child: GeneratedRealizeseuloginWidget1(),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 47.0,
                              child: GeneratedGroup43Widget2(),
                            ),
                            Positioned(
                              left: 467.0,
                              top: 113.0,
                              right: null,
                              bottom: null,
                              width: 441.0,
                              height: 259.0,
                              child: GeneratedImage2Widget(),
                            ),
                            Positioned(
                              left: 597.0,
                              top: 407.0,
                              right: null,
                              bottom: null,
                              width: 248.0,
                              height: 32.0,
                              child: GeneratedRealizeseuloginWidget2(),
                            ),
                            Positioned(
                              left: 540.0,
                              top: 672.0,
                              right: null,
                              bottom: null,
                              width: 368.0,
                              height: 49.0,
                              child: GeneratedBtnUploadPhotoWidget7(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
