import 'package:flutter/material.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedNovasenhaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedConfirmesuanovasenhaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedDigiteeconfirmesuanovasenhaWidget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedBtnUploadPhotoWidget6.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedRecuperaodesenhaWidget2.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedNsteenviaremosumemailparaverificarsuacontaWidget10.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/dailytripapp/generatedcadastroveculowidget1/generated/GeneratedBtngoWidget15.dart';

/* Frame Cadastro - Veículo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroVeculoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 411.0,
        height: 731.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 108.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 36.0,
                child:
                    GeneratedNsteenviaremosumemailparaverificarsuacontaWidget10(),
              ),
              Positioned(
                left: 68.0,
                top: 30.0,
                right: null,
                bottom: null,
                width: 275.0,
                height: 31.0,
                child: GeneratedRecuperaodesenhaWidget2(),
              ),
              Positioned(
                left: 152.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 107.0,
                height: 55.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 615.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedBtnUploadPhotoWidget6(),
              ),
              Positioned(
                left: 66.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 40.0,
                child: GeneratedBtngoWidget15(),
              ),
              Positioned(
                left: 37.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle17Widget1(),
              ),
              Positioned(
                left: 57.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 172.0,
                height: 19.0,
                child: GeneratedConfirmesuanovasenhaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 337.0,
                height: 55.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 19.0,
                child: GeneratedNovasenhaWidget(),
              ),
              Positioned(
                left: 63.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 24.0,
                child: GeneratedDigiteeconfirmesuanovasenhaWidget(),
              )
            ]),
      ),
    ));
  }
}
